Practice 4 pipelinetraining 16

diff --git a/.github/workflows/my-app-pipeline.yml b/.github/workflows/my-app-pipeline.yml
--- a/.github/workflows/my-app-pipeline.yml
+++ b/.github/workflows/my-app-pipeline.yml
@@ -59,32 +59,37 @@ jobs:
     environment: develop
 
   deploy-to-dev:
-    needs: build-and-push
-    runs-on: self-hosted
-    steps:
-      - name: Deploy Redis Container
-        run: |
-          docker stop redisService || true
-          docker rm redisService || true
-          docker run --name redisService -p 6379:6379 -d redis:alpine
+  needs: build-and-push
+  runs-on: self-hosted
+  steps:
+    - name: Deploy Redis Container
+      run: |
+        docker stop redisService || true
+        docker rm redisService || true
+        docker run --name redisService -p 6379:6379 -d redis:alpine
 
-      - name: Pull latest restapp image
-        run: docker pull josedocker14/restapp:${{ needs.build-and-push.outputs.tag }}
+    - name: Pull latest restapp image
+      run: docker pull josedocker14/restapp:${{ needs.build-and-push.outputs.tag }}
 
-      - name: Check if restapp image exists
-        run: docker images | grep josedocker14/restapp || echo "restapp image not found"
+    - name: Check if restapp image exists
+      run: docker images | grep josedocker14/restapp || echo "restapp image not found"
 
-      - name: Deploy restapp Container
-        run: |
-          redisIP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redisService)
-          docker stop restapp || true
-          docker rm restapp || true
-          docker run --name restapp --add-host redis:$redisIP -p 5000:5000 -d josedocker14/restapp:${{ needs.build-and-push.outputs.tag }}
-        shell: /usr/bin/bash -e {0}
+    - name: Deploy restapp Container
+      run: |
+        redisIP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redisService)
+        docker stop restapp || true
+        docker rm restapp || true
+        docker run --name restapp --add-host redis:$redisIP -p 5000:5000 -d josedocker14/restapp:${{ needs.build-and-push.outputs.tag }}
+      shell: /usr/bin/bash -e {0}
 
-      - name: Run Integration Tests
-        run: python -m pytest test/integration -v
-    environment: develop
+    - name: Install Python and pytest
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y python3 python3-pip
+        pip3 install pytest
+
+    - name: Run Integration Tests
+      run: python3 -m pytest test/integration -v
 
   deploy-to-prod:
     needs: deploy-to-dev
